---
# Manually install roles and collections using the following command:
#   ansible-galaxy collection install -r requirements.yml -p ./ -f
#   ansible-galaxy role install -r requirements.yml -p ./ -f
# More info can be found here: https://docs.ansible.com/ansible/latest/user_guide/collections_using.html

roles:
- include: appname.yml

- name: module
  src: https://github.com/ansiblejunky/ansible-examples-repos-role-module.git
  version: master
  scm: git
